services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: safebase_db
      MYSQL_USER: safebase_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
