version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=safebase_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=safebase_db
    depends_on:
      - db
    networks:
      - safebase-network

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - safebase-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=safebase_db
      - MYSQL_USER=safebase_user
      - MYSQL_PASSWORD=your_password
    ports:
      - "3307:3306"
    networks:
      - safebase-network

networks:
  safebase-network:
    driver: bridge
