services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: safebase_db
      MYSQL_USER: safebase_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - safebase-network

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - safebase-network
    depends_on:
      - backend
      
  backend:
    build: ./backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: safebase_user
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: safebase_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - safebase-network

networks:
  safebase-network:
    driver: bridge

volumes:
  db_data: